# https://itnext.io/docker-rails-puma-nginx-postgres-999cd8866b18

version: '3'
volumes:
  uploads_data: {}
  postgres_data: {}
  backups: {}
  log: {}

services:
  app:
    env_file: ./docker/app/.env
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - backups:/var/www/crm/backups
      - uploads_data:/var/www/crm/public/uploads
      - log:/var/www/crm/log
    ports:
      - "25:25"
      - "3000:3000"
    depends_on:
      - db

  db:
    env_file: ./docker/db/.env
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - uploads_data:/var/www/crm/public/uploads
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
