# https://www.youtube.com/watch?v=dF6VQOZPZBM

version: '3'

services:
  db:
    env_file: .env
    image: postgres:11.1-alpine
    volumes:
      - ./db/pgsql/data:/var/lib/postgresql/data

  app:
    env_file: .env
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
