business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 5:00 pm
  holidays:
    - Jan 01, 2015
    - July 4th, 2015
    - December 25th, 2015
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
