default: &default
  adapter:  postgresql
  host:     <%= ENV["PG_HOST"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  encoding: unicode
  pool:     5
  timeout:  5000

development:
  <<: *default
  database: crm_development

test:
  <<: *default
  database: crm_test

production:
  <<: *default
  database: crm_production
